site_name: Notebooks for Data Science

theme:
  name: material
  custom_dir: overrides
nav:
- Home: index.md
- Statistics:
  - Bayesian Statistics: 
    - "bayesian approach for vaccine efficacy": python/BayesianApproachForVaccineEfficacy.ipynb
- Programming:
  - Concepts: python_script.py
  - python:
    - python/01_randomWalks.ipynb
  - "Julia Data Science":
    - julia/data_science/01_preface.ipynb
    - julia/data_science/02_why_julia.ipynb
    - julia/data_science/03_julia_basics.ipynb
    - julia/data_science/04_DataFrames.ipynb
  - "etc":
    - python/UsingPlantuml.ipynb
plugins:
  - mkdocs-jupyter