site_name: Notebooks for Data Science

theme:
  name: material
  custom_dir: overrides
nav:
- Home: index.md
- Statistics:
  - Bayesian Statistics: 
    - "bayesian approach for vaccine efficacy": python/BayesianApproachForVaccineEfficacy.ipynb
- Programming:
    - "Concepts": python_script.py

plugins:
  - mkdocs-jupyter